"""initial warehouse schema

Revision ID: 5bcc8e362093
Revises:
Create Date: 2026-07-17 18:35:53.170782

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bcc8e362093"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic's autogenerate detects tables inside a schema, but never
    # detects "the schema itself is missing" - it assumes it already
    # exists. Added manually so this migration works standalone against
    # a genuinely empty database (autogenerate output starts right below).
    op.execute("CREATE SCHEMA IF NOT EXISTS streaming_dw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_country",
        sa.Column("country_key", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country_code", sa.String(length=10), nullable=False),
        sa.Column("country_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("country_key"),
        sa.UniqueConstraint("country_code"),
        schema="streaming_dw",
    )
    op.create_table(
        "dim_date",
        sa.Column("date_key", sa.Integer(), nullable=False),
        sa.Column("full_date", sa.Date(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("quarter", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("week", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("date_key"),
        schema="streaming_dw",
    )
    op.create_table(
        "dim_genre",
        sa.Column("genre_key", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("genre_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("genre_key"),
        sa.UniqueConstraint("genre_name"),
        schema="streaming_dw",
    )
    op.create_table(
        "dim_platform",
        sa.Column("platform_key", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("platform_key"),
        sa.UniqueConstraint("platform_name"),
        schema="streaming_dw",
    )
    op.create_table(
        "gold_metadata",
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("dataset_name", sa.String(length=100), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("process_id"),
        schema="streaming_dw",
    )
    op.create_table(
        "ingestion_metadata",
        sa.Column("ingestion_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("ingestion_timestamp", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("checksum", sa.String(length=255), nullable=True),
        sa.Column("file_version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ingestion_id"),
        schema="streaming_dw",
    )
    op.create_table(
        "ml_metadata",
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("training_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("model_id"),
        schema="streaming_dw",
    )
    op.create_table(
        "silver_metadata",
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("dataset_name", sa.String(length=100), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("process_id"),
        schema="streaming_dw",
    )
    op.create_table(
        "warehouse_load_metadata",
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=True),
        sa.Column("records_loaded", sa.Integer(), nullable=True),
        sa.Column("load_timestamp", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("load_id"),
        schema="streaming_dw",
    )
    op.create_table(
        "dim_artist",
        sa.Column("artist_key", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("artist_id", sa.String(length=100), nullable=False),
        sa.Column("artist_name", sa.String(length=255), nullable=False),
        sa.Column("country_key", sa.Integer(), nullable=True),
        sa.Column("active_flag", sa.Boolean(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_key"],
            ["streaming_dw.dim_country.country_key"],
        ),
        sa.PrimaryKeyConstraint("artist_key"),
        schema="streaming_dw",
    )
    op.create_table(
        "dim_content",
        sa.Column("content_key", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.String(length=100), nullable=False),
        sa.Column("content_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("duration_minutes", sa.Float(), nullable=True),
        sa.Column("genre_key", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["genre_key"],
            ["streaming_dw.dim_genre.genre_key"],
        ),
        sa.PrimaryKeyConstraint("content_key"),
        schema="streaming_dw",
    )
    op.create_table(
        "fact_content_performance",
        sa.Column(
            "performance_key", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("date_key", sa.Integer(), nullable=True),
        sa.Column("content_key", sa.Integer(), nullable=True),
        sa.Column("artist_key", sa.Integer(), nullable=True),
        sa.Column("genre_key", sa.Integer(), nullable=True),
        sa.Column("platform_key", sa.Integer(), nullable=True),
        sa.Column("country_key", sa.Integer(), nullable=True),
        sa.Column("views", sa.BigInteger(), nullable=True),
        sa.Column("streams", sa.BigInteger(), nullable=True),
        sa.Column("likes", sa.BigInteger(), nullable=True),
        sa.Column("comments", sa.BigInteger(), nullable=True),
        sa.Column("shares", sa.BigInteger(), nullable=True),
        sa.Column("watch_hours", sa.Float(), nullable=True),
        sa.Column("revenue", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("trend_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_key"],
            ["streaming_dw.dim_artist.artist_key"],
        ),
        sa.ForeignKeyConstraint(
            ["content_key"],
            ["streaming_dw.dim_content.content_key"],
        ),
        sa.ForeignKeyConstraint(
            ["country_key"],
            ["streaming_dw.dim_country.country_key"],
        ),
        sa.ForeignKeyConstraint(
            ["date_key"],
            ["streaming_dw.dim_date.date_key"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_key"],
            ["streaming_dw.dim_genre.genre_key"],
        ),
        sa.ForeignKeyConstraint(
            ["platform_key"],
            ["streaming_dw.dim_platform.platform_key"],
        ),
        sa.PrimaryKeyConstraint("performance_key"),
        schema="streaming_dw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_content_performance", schema="streaming_dw")
    op.drop_table("dim_content", schema="streaming_dw")
    op.drop_table("dim_artist", schema="streaming_dw")
    op.drop_table("warehouse_load_metadata", schema="streaming_dw")
    op.drop_table("silver_metadata", schema="streaming_dw")
    op.drop_table("ml_metadata", schema="streaming_dw")
    op.drop_table("ingestion_metadata", schema="streaming_dw")
    op.drop_table("gold_metadata", schema="streaming_dw")
    op.drop_table("dim_platform", schema="streaming_dw")
    op.drop_table("dim_genre", schema="streaming_dw")
    op.drop_table("dim_date", schema="streaming_dw")
    op.drop_table("dim_country", schema="streaming_dw")
    # ### end Alembic commands ###
